### ISSUE TITLE
Build prozent always on 99%

### ISSUE THREAD

**Issue by paule96** [kirkone/vsts-dnx-tasks#1]
Hi :)
Wenn man das Projekt baut ist der build-status immer 99%. Wäre cool wenn er den realen Status anzeigt.

**Comment by kirkone** [comment]
Danke für die Rückmeldung.
Ich glaube nicht dass ich darauf Einfluss nehmen kann, aber ich schau mir das mal an.
Edit:
Ich meine die Prozentangabe bezieht sich auf die Anzahl durchgeführter Tasks. Wenn man also noch 2 andere Tasks mit im Build hat steht da bis zum Abschluss des ersten 33%.

**Comment by paule96** [comment]
Ah okay das ist natürlich schade. Schade das es vs-online nicht hergibt das zutun...
