### ISSUE TITLE
Running the PublishWebPackage task with an invalid web site name gives a strange error and then does not finish the build on failure.

### ISSUE THREAD

**Issue by aranm** [kirkone/vsts-dnx-tasks#10]
Using the "DNX Tasks Azure PublishWebPackage" task I entered the wrong name in the "Web App Name" field. The name I entered was for a web site that did not exist.

The task failed with this error: (Under Build Issues) 

(red X) The website radii was not found. Please specify a valid website name.
(red X) An error occurred during publish.
Method invocation failed because [System.Boolean] does not contain a method named 'TrimEnd'.
(red X) The website <wrong web site name> was not found. Please specify a valid website name.

Where <wrong web site name> was the name of the web site that I entered.

The error message with the exception message is fairly inconsequential but the real thing that is messed up is that the build is still marked as running. It should out after 60 minutes as that is how I have it set up, but it is continuing to run even though it is over the allotted time limit. This bug has shown us an VSTF Bug. How cool is that? You could run up some significant costs if no one was watching it. 👎  The build should fail immediately if we are trying to deploy to a web site with an incorrect name. I will leave it running for a while but I am paying for build minutes so cannot leave it indefinitely. 

I also do not have the "Continue on error" ticked under "Control Options".

**Comment by aranm** [comment]
I cancelled it at 75 minutes. My boss may be a little pissed at me....

**Comment by kirkone** [comment]
This is not good.
I will have a look at this asap.
I had an error similar to this but I thought I did somthing wrong. Now I have a way to reproduce this. Thanks.

**Comment by kirkone** [comment]
Hi, I rebuild this task.
I removed the dependency to msdeploy and replaced it with the Kudu API.
Can you give this please a try and report if this works better for you?

**Comment by dfederm** [comment]
I haven't seen the extremely long times y'all have but I can confirm that the new version using the Kudu API works for me and is actually much faster than msdeploy. That task's time basically cut in half for me :). Great work!

**Comment by kirkone** [comment]
@dfederm thanks for the feedback. I am happy to hear this 😄

**Comment by aranm** [comment]
In order to run the latest code do I need to remove the package and reinstall or do updates to the code automatically propagate to VSTO?

**Comment by dfederm** [comment]
@aranm I should update automatically. If you go to your build definition and click Edit and go to the build task, you should see its version near the bottom of the right pane.

![image](https://cloud.githubusercontent.com/assets/6445614/15235292/da0a5b6a-186e-11e6-8a14-c668d934474c.png)

**Comment by aranm** [comment]
Thanks, I will test if the bug is actually fixed later in the day so you
can close this off.

**Comment by kirkone** [comment]
in some cases I can force the update by disabling and reenabling the extention in the VSTS Manage Extentions section.

As discovered by @dfederm I added the Version number to every Task as description. So you can check if you have the lastest version.
I always update the Readme with the latest versions.

**Comment by kirkone** [comment]
@aranm is this still an issue for you?
