### ISSUE TITLE
PublishWebPackage 0.0.7 seems to be broken

### ISSUE THREAD

**Issue by dfederm** [kirkone/vsts-dnx-tasks#12]
I'm now seeing this error:

2016-05-10T15:21:50.9496597Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\DNX.Tasks.PublishWebPackage\0.0.7\PublishWebPackage.ps1
2016-05-10T15:21:51.2144757Z ##[error]A parameter cannot be found that matches parameter name 'SourceFolder'.

The weird thing is, I don't see any reference to SourceFolder in your code for PublishWebPackage

**Comment by dfederm** [comment]
Ah, it seems like the parameters were just cached. It's weird that VSTS seems to update the extension but leaves the parameter values completely intact, including missing added parameters (even if they have default values) and leaving removed ones.

I just removed and re-added the PublishWebPackage task and it seems to work now.

**Comment by kirkone** [comment]
hi, this seems to be a new behavior by VSTS. not so long ago I could update my tasks and all build definitions with the old version continued to work. I had the same issue today as your one. So I have to update all my build definitions.

I am glad you could fix this so fast for your self and leave a comment. Thanks for that. Hope your work was not interrupted too badly.
