### ISSUE TITLE
RC1 builds broken

### ISSUE THREAD

**Issue by kyschouv** [kirkone/vsts-dnx-tasks#15]
We are still building projects under RC1, and the 0.1.2 release of this extension has broken all of our builds. Please either fix the scripts to detect version, or republish the old code and create _new_ tasks for RC2/CLI builds.

**Comment by kirkone** [comment]
Sorry for that.

I published the "old" tasks here:
[VSTS DNX Tasks RC1](https://marketplace.visualstudio.com/items?itemName=KirKone.vsts-dnx-tasks-rc1)
I hope this helps.

**Comment by kyschouv** [comment]
Thanks. Could you change the guids on the new tasks (to enable side-by-side install), and possibly change the names to reflect that they're on the CLI tools rather than the DNX tools?

**Comment by kirkone** [comment]
Hi, I changed the names of the old ones by addiing "RC1" to every name.
I missed to change the Guid for the tasks. This is fixed with the version I uploaded right now.
Greetings,
KirK
