### ISSUE TITLE
Cannot publish a built nuget package to a VSTS feed

### ISSUE THREAD

**Issue by donaldmcn** [kirkone/vsts-dnx-tasks#18]
When building and attempting to publish to a VSTS internal feed, the publish fails.
The internal feed support currently has some limitations on the version name, and fails if the pre-release version ends in all digits.
A workaround is to append a letter to the version number so you get something that looks like:
1.0.0-pre-x2016070600001 (or whatever you want)
This extension does not allow me to set the build number to contain the prefix letter, since it strips off only the ending number portion of the build generated version

**Comment by kirkone** [comment]
hmm...

I will have a look into this.
I have some projects that publish nuget packages into the feed in VSTS and there are no problems. I will have a look in this projects to see what exactly is configured.

so long,
KirK

**Comment by donaldmcn** [comment]
So I took a closer look at my build, and it turns out the error I was seeing was from a second build step, which is the nugget publish that is part of VSTS.

It looks like the error is with that build step, because it is trying to publish the package twice, I am not sure why.

Anyways, it seems your extension is working correctly, and the build label is find for pre-release.

Thanks, don

**Comment by donaldmcn** [comment]
After a bit more investigation, it looks like the issue is this:

Dotnet pack will produce both a *.nupkg, and a *.symbols.nupkg.

When working with a local VSTS feed, the NuGet publish build step, by default will try to push all nupkg files it finds, based on the file search pattern given. The conflict comes from trying to push the symbols nupkg to the same feed.

I am not sure how to resolve this for internal feeds, since there is not a symbols feed that corresponds to the feed that I have setup in our VSTS instance.

A not great work around is to add a delete file build step before the Nuget Publish that deletes the symbols nupkg.

don

**Comment by kirkone** [comment]
Hi,

I can see the Problem here.
You are right that the `dotent pack` command generates 2 .nupkg files.
I do not know if there is a possibility to get `dotnet pack` command only create the `*.nupkg` and not the `*.symbols.nupkg` file.

The solution for me was to use the following `Path/Pattern to nupkg`:

```
$(Build.StagingDirectory)\Pack\**\*.nupkg;-:$(Build.StagingDirectory)\Pack\**\*.symbols.nupkg
```

This will only select the file without the symbols and you do not get the error anymore.

I hope this helps and sorry for the late response.
CU
KirK

**Comment by kirkone** [comment]
@donaldmcn can this be closed?

**Comment by donaldmcn** [comment]
yes
