### ISSUE TITLE
issue while building nuget package

### ISSUE THREAD

**Issue by srivatsamarichi** [kirkone/vsts-dnx-tasks#20]
Hi,
I get error upon building my nuget pkg task in my VSTS build. I followed the instructions mentioned but still unable to succeed. Can you help me out here?

PFA build logs for your reference.

[2_Build Nuget Package MyHealth.Web.txt](https://github.com/kirkone/vsts-dnx-tasks/files/414690/2_Build.Nuget.Package.MyHealth.Web.txt)

Thanks,
Srivatsa

**Comment by kirkone** [comment]
Hello @SrivatsaMarichi 
sorry for being late here at your issue.
it seems like somthing is wrong with your folder structure. are you sure there is a "MyHealth.Web" folder under the "src" folder?
it has to look like this:

```
rootfolder
  src
    MyHealth.Web
```
