### ISSUE TITLE
Build Web Package doesn't display publish errors

### ISSUE THREAD

**Issue by veccsolutions** [kirkone/vsts-dnx-tasks#22]
It looks like the build web package powershell script was modified to display errors on build in version 0.1.13. But on publish it doesn't display the errors. On line 115 of BuildWebPackage, removing the 2>$1 from the end of the line fixed it for me.

**Comment by kirkone** [comment]
You are right, I will fix this asap.
Thanks for the tip.

**Comment by kirkone** [comment]
Hi,
after some diggin into this I found [this](https://github.com/dotnet/cli/issues/443)
I did some tests and did not come up with a reliable solution how to detect if errors occur in the publish prozess.
I will continue serching a solution for this.

**Comment by kirkone** [comment]
Hopefully fixed with release [0.1.18](https://github.com/kirkone/vsts-dnx-tasks/releases/tag/v0.1.18)
