### ISSUE TITLE
TFS 2015 Version 14.X

### ISSUE THREAD

**Issue by avarndell** [kirkone/vsts-dnx-tasks#25]
I don't see the task.

**Comment by kirkone** [comment]
Hi,

is there any message when installing?
did the extension show up as active?

Sorry, I do not have an TFS 2015 on hand but I will try to get my hands on one.

**Comment by kirkone** [comment]
A note on the side:
You mentioned in your question in the VS Marketplace that you are using TFS 2015 version 14.113.26306.0
A quick look [here](https://blogs.msdn.microsoft.com/tfssetup/2013/11/21/what-version-of-team-foundation-server-do-i-have/) showed up you are using the RC1 of the Update 4.
I do not think this is the reason why the extension is not working but I thought it is a good idea to point this out.

**Comment by MacMcDell** [comment]
I don't see the task either. Using VSTFS 2105 
Microsoft Visual Studio Team Foundation Server
Version 14.114.26403.0
Install KirKone.vsts via extensions, install to defaultCollection.
The items don't appear anywhere in add tasks. 
![image](https://user-images.githubusercontent.com/1512821/32462631-f2c00a98-c2ee-11e7-9a84-916f85baea08.png)

![image](https://user-images.githubusercontent.com/1512821/32462713-3a2d6bc8-c2ef-11e7-9263-93704a4afa13.png)

**Comment by kirkone** [comment]
hi,
very strange.
What agent version do you run?
Maybe it has something to do with the minimal agent version I set in the Tasks.

**Comment by MacMcDell** [comment]
OSVersion: 6.3.9600
Agent Version: 1.95.4
Agent PS: 3.1.0

**Comment by kirkone** [comment]
Ahh, there is the problem: ["minimumAgentVersion": "1.99.5"](https://github.com/kirkone/vsts-dnx-tasks/blob/bf0bdf15466b59c1e3368b2a186a0316bc91612b/VSTS.DNX.Tasks.AddVirtualApp/task.json#L23)
I am sure the tasks will not show up because they will not match the requirements. I think it should be save to lower the min version down to 1.95.4
This should at least solve the problem for you @MacMcDell 
I will get a new version ready soon.

**Comment by MacMcDell** [comment]
ok cool thank you. Strange, I was under the impression I was running the latest agent available for TFS 2015.

**Comment by kirkone** [comment]
I did not have a TFS 2015 on hand to test it with so I guessed the version number and I was a little of I think 😄

**Comment by kirkone** [comment]
@MacMcDell can you please give this a try [Release for Version 0.1.30](https://github.com/kirkone/vsts-dnx-tasks/releases/tag/v0.1.30)
Please give feedback how it is going. If it is working I will push the new version to the marketplace.

**Comment by MacMcDell** [comment]
I can now see your custom tasks. Thanks!
