### ISSUE TITLE
hardcoding string - "src"

### ISSUE THREAD

**Issue by lchodkiewicz** [kirkone/vsts-dnx-tasks#3]
Unfortunately in the script path we have recived hardcoding string - "src".
Perhaps it would be better to get the opportunity to set up the project path?

**Comment by kirkone** [comment]
I am considering to have an option to set this path.
In the mean time you can specify your project name like so: `"\..\Sample.Web"`

**Comment by kirkone** [comment]
Hi,

I uploaded a new version where you can specify the folder where your project folders are.
Can you please give it a try if this is what you need?

Thanks

**Comment by lchodkiewicz** [comment]
It's looks pretty nice, thanks for that :)
