### ISSUE TITLE
Add support for generic dnx command

### ISSUE THREAD

**Issue by dfederm** [kirkone/vsts-dnx-tasks#7]
It would be great if you also added a generic dnx task that takes in the command as input. That way people can do stuff like "dnx test" or basically anything else they wanted to do while still assuming dnvm and dnx are installed.

For now I'm just using the "Command line" task to basically do the same thing, but it assumes that some previous task (your dnx build web package one) has already installed it so "dnx" just works.

**Comment by kirkone** [comment]
Nice idea, I will try to get this in.

**Comment by kirkone** [comment]
maybe #13 is something to get this working.
When the CLI can installed as a seperate task you can use the commandline task to run what you want.

Did I get this right?

**Comment by dfederm** [comment]
Yup, exactly.
