### ISSUE TITLE
WebSiteLocation added as required but unused

### ISSUE THREAD

**Issue by dfederm** [kirkone/vsts-dnx-tasks#8]
I'm getting the error:
Cannot bind argument to parameter 'WebSiteLocation' because it is an empty string.

I updated my input to provide the value, but while investigate I noticed that in PublishWebPackage.ps1, you take in $WebSiteLocation as a mandatory param but never use it in the script.

Just wanted to bring it to your attention :)

**Comment by kirkone** [comment]
fixed with
cd80b7114b2bc4cc4f41a47b3c196e0f22fd8cdb
